### ISSUE TITLE
Usage with phoenix framework

### ISSUE THREAD

**Issue by alexjp** [MyMedsAndMe/marco_polo#19]
Hi,

Firstly, thanks for the awesome package. Made me look at some very interesting features of orientdb.

Could this package be used in a phoenix framework project, with configuration on config.exs ?

Thanks!

**Comment by whatyouhide** [comment]
Hey @alexjp,

thanks for the kind words! I'm not sure what you mean by 

> used in a phoenix framework project, with configuration on config.exs

If you mean something like "can this be used similarly to Ecto, where I store the connection options (username, password, host etc.) in `config.exs` and most of the stuff then is done automagically", then you probably can't. Let me explain better: this is a binary **driver** for OrientDB, meaning it's very low-level and doesn't provide lots of facilities.

Usually, you use these kind of drivers (similar ones in scope are [postgrex](https://github.com/ericmj/postgrex) or [mongodb](https://github.com/ericmj/mongodb)) you may want to pool them in some way, for example using [poolboy](https://github.com/devinus/poolboy).
Once you have poolboy setup, you could specify the pool configurations in `config.exs`. These configs would include the arguments to pass to `MarcoPolo.start_link/1`, thus they'd include the connection options as well. You would still have to manually "read" them from `config.exs` (with `Application.get_env/2` probably) when you create the supervision tree that includes poolboy.

That said, we're starting to work on an Ecto adapter so hopefully in a while you'll be able to use OrientDB just like Postgres with Phoenix.

Hope I've been clear :), let me know!

**Comment by alexjp** [comment]
Yes,

I started testing it with an phoenix app, but i was doing everything "manually". I will take a look at poolboy, seems to be what i was missing.

Thanks!

**Comment by whatyouhide** [comment]
@alexjp no problem, glad to help :)
Closing this for now, feel free to reopen if you need anything!
