### ISSUE TITLE
Working with Erlang

### ISSUE THREAD

**Issue by mvbaffa** [MyMedsAndMe/marco_polo#20]
Hi,

Does this driver works with Erlang ?

Thanks

**Comment by whatyouhide** [comment]
Hey @mvbaffa, yes, being written in Elixir this driver should be usable in Erlang as well.

```erlang
'Elixir.MarcoPolo':start_link(...).
```

That said, I never tried doing it and I won't be able to try for a couple of weeks; I can point you to the [guide for running Elixir code in Erlang on the Elixir intro guide](http://elixir-lang.org/crash-course.html#adding-elixir-to-existing-erlang-programs). Let me know if I can help in any other way.

PS the only thing I wouldn't know how to handle is dependencies, i.e., you would need to add MarcoPolo as a dependency of your project, then MarcoPolo has other dependencies and so on.

**Comment by whatyouhide** [comment]
Closing this as working with Elixir libraries in Erlang is not a MarcoPolo-specific issue.
