### ISSUE TITLE
Slow response time

### ISSUE THREAD

**Issue by ospaarmann** [MyMedsAndMe/marco_polo#21]
When using marco_polo in a very simple phoenix app I get very slow response times. Returning 10 results (without any associations) as json takes about 200ms. The same request using Ecto and postgresql takes around 10ms. 

OrientDB is running on the same machine, so network lag cannot be the issue. When I use  the OrientDB Studio (Webinterface) the request takes around 30ms to render. I tested this using a simple worker and a pool of workers using poolboy. The latter was the slowest with ~250ms per request.

200ms might sound acceptable. But part of the reason I'm using Elixir / Phoenix is speed. And if the database connection slows my app down by factor 20 it is a problem.

**Comment by whatyouhide** [comment]
Hey @ospaarmann, thanks for the report. I'll take a look at this in the afternoon :)

**Comment by ospaarmann** [comment]
Thanks.

My custom repo module:

    defmodule MyApp.OrientRepo do

      def start_link(opts \\ []) do
        {:ok, conn} = MarcoPolo.start_link(opts)
        Agent.start_link(fn -> conn end, name: __MODULE__)
        {:ok, self}
      end

      def command(query) do
        Agent.get(__MODULE__, fn conn ->
          MarcoPolo.command conn, query
        end)
      end
    end

my app where I add the worker

    defmodule MyApp do
      use Application

      # See http://elixir-lang.org/docs/stable/elixir/Application.html
      # for more information on OTP Applications
      def start(_type, _args) do
        import Supervisor.Spec, warn: false

        children = [
          # Start the endpoint when the application starts
          supervisor(MyApp.Endpoint, []),
          # Here you could define other workers and supervisors as children
          # worker(MyApp.Worker, [arg1, arg2, arg3]),
          worker(MyApp.OrientRepo, [[user: "root", password: "password", connection: {:db, "mydatabase", :graph}]])
        ]

        # See http://elixir-lang.org/docs/stable/elixir/Supervisor.html
        # for other strategies and supported options
        opts = [strategy: :one_for_one, name: MyApp.Supervisor]
        Supervisor.start_link(children, opts)
      end

      # Tell Phoenix to update the endpoint configuration
      # whenever the application is updated.
      def config_change(changed, _new, removed) do
        MyApp.Endpoint.config_change(changed, removed)
        :ok
      end
    end

The Controller that does the actual query (very simple one just for testing). The DB contains around 20 records so this shouldn't be an issue...

    defmodule MyApp.LinkController do
      use MyApp.Web, :controller

      def index(conn, _params) do
        query = "SELECT FROM link"
        {:ok, %{response: links}} = MyApp.OrientRepo.command(query)
        render conn, links: links
      end
    end

**Comment by whatyouhide** [comment]
Hey there @ospaarmann, I played with MarcoPolo today and with the scenario you described. I didn't get even close to your benchmarks: the most it took to query a class with 10 records in it was ~10ms (for the first query, then ~5ms for further queries and note I have binary debugging enabled in my OrientDB server, which I assume adds quite a lot of time to the command).

Let's try to find the cause of the issue. First, could you try to reproduce the issue in IEx? I'm not sure how you're measuring the time it takes to execute the query but I'm guessing you're looking at the response time from Phoenix. Anyways, reproducing it in a simpler environment will for sure make things easier.

To isolate the issue, I'd say create a new Mix application with only `:marco_polo` as a dependency, then run IEx and measure how long it takes to execute the query:

```elixir
iex> {:ok, conn} = MarcoPolo.start_link(user: ..., password: ..., connection: ...)
{:ok, #PID<...>}
iex> :timer.tc(fn -> MarcoPolo.command(conn, "SELECT FROM link") end) |> elem(0)
...
```

and let me know what you get. If you still have the same results let me know :) Btw, I'm available as whatyouhide on the #elixir-lang IRC as well if you want faster feedback :).

**Comment by ospaarmann** [comment]
I tested a simple query in my IEx (using my phoenix app) and the response time was much better. @whatyouhide then suggested running the app in production mode. This did the trick and the response time went down to 5-8ms for a normal OTP worker and using a pool of workers with poolboy. Hope that helps anyone with similar issues.
