### ISSUE TITLE
Library status

### ISSUE THREAD

**Issue by pdilyard** [MyMedsAndMe/marco_polo#22]
Not sure if an issue is the best place to ask this, but here it is:

Is this repo still being maintained? Are there future plans for it? I'm looking into using it for work, but I need to ensure that it's not going to go out of date in a couple months.

**Comment by whatyouhide** [comment]
The repo is indeed alive :). I took a long break from working on it but we just reserved the next couple of weeks to fix bugs and add a couple of new features to marco_polo, so you should be good to go :).

**Comment by pdilyard** [comment]
@whatyouhide awesome, thanks!
