### ISSUE TITLE
Importing JSON databases through the REST API

### ISSUE THREAD

**Issue by whatyouhide** [MyMedsAndMe/marco_polo#25]

**Comment by whatyouhide** [comment]
The documentation around this is extremely scarce (it's [here](http://orientdb.com/docs/last/OrientDB-REST.html#import)) and slightly confusing (e.g., it says to `POST` to `http://<server>:[<port>]/import/<database>` but then in the example it `POST`s to `http://localhost:2480/import/`).

Let's assume we have a file called `db` that is the result of exporting the `MarcoPoloTest` database, like this:

```bash
curl --user root:root -X GET 'http://localhost:2480/export/MarcoPoloTest' \
  -H 'Accept-Encoding: gzip,deflate' \
  -H 'Content-Type: application/json' \
  > db.gzip
```

Then, let's assume I've unzipped `db.gzip` to `db` and I'm connected to the `MarcoPoloTest` database by doing:

```bash
curl -v --user root:root -X GET 'http://localhost:2480/connect/MarcoPoloTest' \
  -H 'Accept-Encoding: gzip,deflate'
```

```http
HTTP/1.1 204 OK
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Date: Fri Mar 11 13:30:53 CET 2016
Content-Type: text/plain; charset=utf-8
Server: OrientDB Server v.2.2.0-beta (build develop@r4cbc24a66f17f023a2e59da300a29b91fdb5d1fa; 2016-02-22 17:46:44+0000)
Connection: Keep-Alive
Set-Cookie: OSESSIONID=OS1457699453268-4591488868473251284; Path=/; HttpOnly
Content-Length: 0
```

If I make a `POST` request to `http://localhost:2480/import/<database>` with `Content-Type: application/json` and the JSON-encoded database in the body (which is what I expected to work), it complains that the request is not `multipart/form-data` (still not sure why it should be, but [these lines](https://github.com/orientechnologies/orientdb/blob/7e6e319fa04378c3b02c1ecc6bb49adb89aef457/server/src/main/java/com/orientechnologies/orient/server/network/protocol/http/command/post/OServerCommandPostImportDatabase.java#L49-L50) in the OrientDB source confirm that the check is made there):

```bash
curl -v --user root:root -X POST 'http://localhost:2480/import/MarcoPoloTest' \
  -H 'Accept-Encoding: gzip,deflate' \
  -H 'Content-Type: application/json' \
  --cookie 'OSESSIONID=OS1457699453268-4591488868473251284' \
  -d @db
```

```http
HTTP/1.1 405 Request is not multipart/form-data
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Date: Fri Mar 11 13:32:53 CET 2016
Content-Type: text/plain; charset=utf-8
Server: OrientDB Server v.2.2.0-beta (build develop@r4cbc24a66f17f023a2e59da300a29b91fdb5d1fa; 2016-02-22 17:46:44+0000)
Connection: Keep-Alive
Set-Cookie: OSESSIONID=OS1457699453268-4591488868473251284; Path=/; HttpOnly
Content-Length: 34

Request is not multipart/form-data
```

If I do what the error message suggests and change the content-type to `multipart/form-data` by uploading a file, I still get an error:

```bash
curl -v -X POST 'http://localhost:2480/import/MarcoPoloTest' \
  -H 'Accept-Encoding: gzip,deflate' \
  --cookie 'OSESSIONID=OS1457703457177-2218910698106246248' \
  -F file=@db
```

```http
HTTP/1.1 405 Wrong request: Expected CR/LF
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Date: Fri Mar 11 14:40:14 CET 2016
Content-Type: text/plain; charset=utf-8
Server: OrientDB Server v.2.2.0-beta (build develop@r4cbc24a66f17f023a2e59da300a29b91fdb5d1fa; 2016-02-22 17:46:44+0000)
Connection: Keep-Alive
Set-Cookie: OSESSIONID=OS1457703457177-2218910698106246248; Path=/; HttpOnly
Content-Length: 29
* HTTP error before end of send, stop sending

Wrong request: Expected CR/LF
```

This error should come from [here](https://github.com/orientechnologies/orientdb/blob/7e6e319fa04378c3b02c1ecc6bb49adb89aef457/server/src/main/java/com/orientechnologies/orient/server/network/protocol/http/multipart/OHttpMultipartRequestCommand.java#L122-L123).

This is taking me far too much time (and the documentation isn't helping at all), so it would be super-nice if someone from @MyMedsAndMe/voyagers could help in finding a `curl` command that works here :).

**Comment by yelps** [comment]
Hey Andrea,
I suppose it's related to the same problem I had before. The reason behind the weird error message is that http import doesn't support the "- merge" option and ends up in a indiscriminate state.

There is a request open for this issue:
http://www.prjhub.com/#/issues/5923

It suppose to be fixed in OrientDB 2.2 Beta which is available here:

http://orientdb.com/orientdb-labs/

**Comment by whatyouhide** [comment]
Hey @yelps, I assumed this wasn't related to the `-merge` option as I'm importing a dumped database to a freshly created database, so there should be no need for any kind of merging. Also, I am indeed running on 2.2-beta (this can be seen in the `Server` header in the responses above, which is `OrientDB Server v.2.2.0-beta (build develop@r4cbc24a66f17f023a2e59da300a29b91fdb5d1fa; 2016-02-22 17:46:44+0000)`).

**Comment by yelps** [comment]
Oh, I see. Then it's probably best to ask the support team of Orient Technologies.

**Comment by simonewebdesign** [comment]
I managed to reproduce the same error:

```bash
curl --user root:secret -X POST 'http://localhost:2480/import/demo_db' \
      -H 'Accept-Encoding: gzip,deflate' \
      -H 'Content-Type: multipart/form-data' \
      --cookie 'OSESSIONID=OS1457699453268-4591488868473251284; Path=/; HttpOnly' \
      --form "filename=@db.gzip"
```
```
Wrong request: Expected CR/LF⏎
```
I tried decompressing the gzip file, converting LF to CR LF while recompressing it, but still no luck.

Anyway I think this is something that should be addressed in the OrientDB repo, as I would expect the REST API to be able to accept `application/json` in the first place.

**Comment by whatyouhide** [comment]
@simonewebdesign absolutely, it makes much more sense to POST a JSON database as just JSON binary with `Content-Type: application/json` instead of having to go through the hustle of encoding it as multipart.

**Comment by whatyouhide** [comment]
This is on hold waiting for @tglman to let us know when a release including the changes described in https://github.com/orientechnologies/orientdb/issues/5837 and implemented in https://github.com/orientechnologies/orientdb/commit/253e3cf7f3ac001fbb589a6e952bb038364d0faf will be released in a new OrientDB 2.2 beta version.

**Comment by tglman** [comment]
OrientDB 2.2 beta2 has been released.
here the link: http://orientdb.com/download.php?email=unknown@unknown.com&file=orientdb-community-2.2.0-beta.tar.gz&os=multi

**Comment by whatyouhide** [comment]
This was hopefully implemented in https://github.com/MyMedsAndMe/marco_polo/commit/e567aefe317115e8aa0eb940799cf1da2adb9fc5. I don't fully trust the OrientDB side yet, but I think we're doing everything right on the client (MarcoPolo) side, so I'm gonna close this for now.
