### ISSUE TITLE
Support "push requests" for changes in the cluster configuration

### ISSUE THREAD

**Issue by whatyouhide** [MyMedsAndMe/marco_polo#27]

**Comment by whatyouhide** [comment]
This is on hold waiting for @tglman to fill in the documentation for `REQUEST_PUSH_DISTRIB_CONFIG` and `REQUEST_PUSH_LIVE_QUERY` as described in https://github.com/orientechnologies/orientdb/issues/5871 and https://github.com/orientechnologies/orientdb/issues/5873.

**Comment by tglman** [comment]
update some docs

**Comment by whatyouhide** [comment]
This should have been fixed in https://github.com/MyMedsAndMe/marco_polo/commit/3ee72391fbecdca2c5cdc7344e97393599321f47, I have no easy way to try this (even if it *should* be straightforward), so if any of @MyMedsAndMe/voyagers will have the chance to try this, please report any issues :).
