### ISSUE TITLE
Does not work mix test test/

### ISSUE THREAD

**Issue by fukaoi** [MyMedsAndMe/marco_polo#29]
My testing enviroment 

orientdb-community-2.1.8(Mac OSX 10.11.3)
orientdb-community-2.1.13(CentOS6.7)

Elixir version:1.2.3
marco_polo:0.2.1

Error exception below were there
```bash

  #mix test  test/
** (ErlangError) erlang error: :enoent
    (elixir) lib/system.ex:450: System.cmd("orientdb-console", ["SET ignoreErrors true;\nDROP DATABASE remote:localhost/MarcoPoloTest root root;\nDROP DATABASE remote:localhost/MarcoPoloTestGenerated root root;\nDROP DATABASE remote:localhost/MarcoPoloToDrop root root;\nSET ignoreErrors false;\n\nCREATE DATABASE remote:localhost/MarcoPoloTest root root plocal;\nCREATE DATABASE remote:localhost/MarcoPoloToDrop root root memory;\n"], [stderr_to_stdout: true])
    test/test_helper.exs:47: anonymous fn/1 in :elixir_compiler_1.__FILE__/1
    test/test_helper.exs:82: (file)
    (elixir) lib/code.ex:363: Code.require_file/2
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2


```
please respond to this matter...

**Comment by whatyouhide** [comment]
As stated in the [CONTRIBUTING guide](https://github.com/MyMedsAndMe/marco_polo/blob/master/CONTRIBUTING.md#testing-locally), you need to have the `orientdb-console` command available (`orientdb-console` should the OrientDB console, it can just be a "proxy" command). This is what the error message is saying (`:enoent` means something was not found, in this case `orientdb-console`. I'll write a more helpful error message for this case.

**Comment by fukaoi** [comment]
Thank you for reply.
I had missed it  file, and "mix test" worked now.
