### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by austinsmorris** [MyMedsAndMe/marco_polo#31]
I was wondering if you could push a new release to hex.  The 0.2.1 version is hard coded to the connection 1.0.0 release candidate, that is now released and this hard coded dependency is now incompatible with current projects...

**Comment by austinsmorris** [comment]
Note that the master branch has `{:connection, "~> 1.0.0"}`, so it is good to go.

**Comment by whatyouhide** [comment]
Hey @austinsmorris, we're working on a bunch of new features for MarcoPolo and will likely release a `v0.3.0` version soon. I can probably do a `v0.2.2` backport release though, I'll ping you when it's ready :)

**Comment by whatyouhide** [comment]
Released `v0.2.2`.

**Comment by austinsmorris** [comment]
Awesome, thanks! 👍
