### ISSUE TITLE
v0.3.0 status?

### ISSUE THREAD

**Issue by austinsmorris** [MyMedsAndMe/marco_polo#33]
Hi @whatyouhide,

I was wondering if you could update us on the status of v0.3.0, since OrientDB 2.2 is expected by the end of the month?  Are you planning to support #11?

Thanks for all the great work!

**Comment by whatyouhide** [comment]
Hey @austinsmorris, OrientDB 2.2.0-beta is introducing a bunch of backwards-incompatible changes so it will take me a while to fix things up. No plan to support #11 yet, making MarcoPolo work with 2.2 has the priority now.
