### ISSUE TITLE
Update readme examples to work "out of the box"

### ISSUE THREAD

**Issue by maxtors** [MyMedsAndMe/marco_polo#34]
Trying to copy the examples, for example:
`{:ok, conn} = MarcoPolo.start_link(user: "admin",
                                   password: "admin",
                                   connection: {:db, "GratefulDeadConcerts"})`

Does not work, and users might be wondering what is wrong, the "connection" map needs either a `:graph` or `:document` atom provided. 

Ref:
`Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.2.5) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> {:ok, conn} = MarcoPolo.start_link(user: "admin",
...(1)>                                    password: "admin",
...(1)>                                    connection: {:db, "GratefulDeadConcerts"})
{:ok, #PID<0.130.0>}
** (EXIT from #PID<0.126.0>) an exception was raised:
    ** (ArgumentError) invalid connection type, valid ones are :server or {:db, name, type}
        lib/marco_polo/connection/auth.ex:84: MarcoPolo.Connection.Auth.op_and_args_from_connection_type/1
        lib/marco_polo/connection/auth.ex:58: MarcoPolo.Connection.Auth.op_and_connection_args/1
        lib/marco_polo/connection/auth.ex:46: MarcoPolo.Connection.Auth.authenticate/1
        lib/marco_polo/connection.ex:131: MarcoPolo.Connection.connect/2
        lib/connection.ex:623: Connection.enter_connect/5
        (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

Interactive Elixir (1.2.5) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
21:06:22.445 [error] GenServer #PID<0.130.0> terminating
** (ArgumentError) invalid connection type, valid ones are :server or {:db, name, type}
    lib/marco_polo/connection/auth.ex:84: MarcoPolo.Connection.Auth.op_and_args_from_connection_type/1
    lib/marco_polo/connection/auth.ex:58: MarcoPolo.Connection.Auth.op_and_connection_args/1
    lib/marco_polo/connection/auth.ex:46: MarcoPolo.Connection.Auth.authenticate/1
    lib/marco_polo/connection.ex:131: MarcoPolo.Connection.connect/2
    lib/connection.ex:623: Connection.enter_connect/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: nil
State: %{live_query_tokens: #HashDict<[]>, opts: [host: "localhost", port: 2424, user: "admin", password: "admin", connection: {:db, "GratefulDeadConcerts"}], protocol_version: nil, queue: {[], []}, schema: nil, session_id: nil, socket: nil, tail: "", transaction_id: 1}`

**Comment by whatyouhide** [comment]
Hey @maxtors, thanks for the report! The README is updated to reflect the changes in the master branch. In particular, OrientDB dropped the database type when connecting so `:graph`/`:document` are not supported any more. If using MarcoPolo from hex.pm, you should always refer to the documentation for the correct MarcoPolo version (at http://hexdocs.pm/marco_polo). Thanks :)!
