### ISSUE TITLE
Time out when connecting to OrientDB 2.2.6

### ISSUE THREAD

**Issue by onelesd** [MyMedsAndMe/marco_polo#41]
Installed OrientDB on OSX via docker with:
```
docker run -d --name orientdb -p 2424:2424 -p 2480:2480 -e ORIENTDB_ROOT_PASSWORD=root orientdb:latest
```
Created the otp_ice database through the web console on port 2480.

When trying to start_link I get a timeout error:

```
iex(1)> {:ok, conn} = MarcoPolo.start_link(user: "admin", password: "admin", connection: {:db, "otp_ice", :graph})
** (EXIT from #PID<0.265.0>) time out

Interactive Elixir (1.3.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> [error] GenServer #PID<0.267.0> terminating
** (stop) time out
Last message: nil
State: %{live_query_tokens: #HashDict<[]>, opts: [host: "localhost", port: 2424, user: "admin", password: "admin", connection: {:db, "otp_ice", :graph}], protocol_version: 36, queue: {[], []}, schema: nil, session_id: nil, socket: #Port<0.7584>, tail: "", transaction_id: 1}```

**Comment by whatyouhide** [comment]
@onelesd hey there, thanks for the report. What version of MarcoPolo and OrientDB are you using?

**Comment by onelesd** [comment]
Thanks for the quick reply!

marco_polo 0.2.2
OrientDB 2.2.6

**Comment by onelesd** [comment]
Elixir 1.3.2

Mentioning because there are some unsafe warnings during compile about setting variables inside case/if/cond blocks. I've typically found the warnings to be harmless...

**Comment by whatyouhide** [comment]
@onelesd hey there, sorry for the late reply! Those warnings are very likely harmless, yeah, and the behaviour around scopes and variables didn't change (we just warn about it). Can you try out MarcoPolo master and see if you have the same problem please? :)

**Comment by onelesd** [comment]
Using the master branch I am able to connect. Thanks!

**Comment by whatyouhide** [comment]
Awesome, watch out for the next release then, still not sure when it's gonna go out though. :)
